import { describe, expect, it } from 'vitest'
import packageJson from '../package.json'
import { generateHtmlReport } from '../src/engine/reporter/html.js'
import type { ProductModel, TestScenario, TestResult } from '../src/types/index.js'
import { VibeConfigSchema } from '../src/types/config.js'

describe('generateHtmlReport verification status classification', () => {
  const config = VibeConfigSchema.parse({ url: 'http://localhost:3000' })
  const scenarios: TestScenario[] = [
    {
      id: 'verified',
      name: 'Outcome verified',
      route: '/',
      priority: 'high',
      steps: [
        { action: 'navigate', url: '/', description: 'Go home' },
        { action: 'assert', selector: '[data-testid="page"]', value: 'Dashboard', description: 'Primary heading present' },
      ],
      expected_outcome: 'Primary heading is visible',
      is_gap: false,
      generated_by: 'heuristic',
    },
    {
      id: 'smoke',
      name: 'Smoke check',
      route: '/',
      priority: 'medium',
      steps: [
        { action: 'navigate', url: '/', description: 'Go home' },
      ],
      expected_outcome: 'Page loads',
      is_gap: false,
      generated_by: 'heuristic',
    },
    {
      id: 'failed',
      name: 'Broken flow',
      route: '/',
      priority: 'low',
      steps: [
        { action: 'navigate', url: '/', description: 'Go home' },
      ],
      expected_outcome: 'Always works',
      is_gap: false,
      generated_by: 'heuristic',
    },
  ]

  const productModel: ProductModel = {
    project_name: 'demo',
    url: 'http://localhost:3000',
    framework: 'react-spa',
    codebase_path: '/tmp/vibe-demo',
    scanned_at: '2026-01-01T00:00:00.000Z',
    routes: [{ path: '/', type: 'page', requires_auth: false, dynamic_segments: [] }],
    behaviours: [],
    coverage: { '/': { tested: true, scenarios: ['verified'] , frameworks: [] } },
    gaps: [],
    scenarios,
  }

  const results: TestResult[] = [
    {
      scenario: scenarios[0],
      status: 'pass',
      duration_ms: 10,
      step_logs: [],
      verification_status: 'outcome_verified',
    },
    {
      scenario: scenarios[1],
      status: 'pass',
      duration_ms: 15,
      step_logs: [],
      verification_status: 'smoke_check_passed',
    },
    {
      scenario: scenarios[2],
      status: 'fail',
      duration_ms: 20,
      step_logs: [],
      failure_reason: 'Fixture failure',
      verification_status: 'not_verified',
    },
  ]

  it('shows outcome-labeled status buckets in the report summary', async () => {
    const report = await generateHtmlReport(results, productModel, config, [], [], undefined)

    expect(report).toContain('<span class="badge outcome_verified">Outcome verified</span>')
    expect(report).toContain('<span class="badge smoke_check_passed">Smoke check passed</span>')
    expect(report).toContain('<span class="badge not_verified">Not verified</span>')
    expect(report).toMatch(/<div class="summary-stat outcome"><div class="num">1<\/div><div class="lbl">Outcome verified<\/div><\/div>/)
    expect(report).toMatch(/<div class="summary-stat smoke"><div class="num">1<\/div><div class="lbl">Smoke check passed<\/div><\/div>/)
    expect(report).toMatch(/<div class="summary-stat not"><div class="num">1<\/div><div class="lbl">Not verified<\/div><\/div>/)
  })

  it('uses current package version in the footer', async () => {
    const report = await generateHtmlReport(results, productModel, config, [], [], undefined)
    expect(report).toContain(`<footer>Generated by <strong>vibe-test</strong> v${packageJson.version}`)
  })
})
