import { TestResult, ProductModel, CoverageGapSuggestion } from '../../types/index.js'
import { VibeConfig } from '../../types/config.js'
import type { MemoryRecommendations } from '../memory/index.js'
import type { PageExploration, InteractionOutcome, ApiObservation } from '../browser/explorer.js'
import fs from 'fs/promises'

export async function generateHtmlReport(
  results: TestResult[],
  productModel: ProductModel,
  config: VibeConfig,
  explorations: PageExploration[],
  coverageGaps: CoverageGapSuggestion[],
  recommendations?: MemoryRecommendations
): Promise<string> {
  const passed  = results.filter(r => r.status === 'pass')
  const failed  = results.filter(r => r.status === 'fail')
  const errored = results.filter(r => r.status === 'error')
  const totalMs = results.reduce((sum, r) => sum + r.duration_ms, 0)

  const totalElements = explorations.reduce((s, e) => s + e.elements_discovered, 0)
  const totalApis = explorations.reduce((s, e) => s + e.api_calls.length, 0)
  const apiErrors = explorations.reduce((s, e) => s + e.api_calls.filter(a => a.isError).length, 0)
  const brokenElements = explorations.reduce((s, e) => s + e.interactions.filter(i => i.result === 'error').length, 0)

  const screenshotCache: Record<string, string> = {}
  const stepScreenshotCache: Record<string, string> = {}
  for (const result of results) {
    if (result.screenshot_path) {
      try {
        const buf = await fs.readFile(result.screenshot_path)
        screenshotCache[result.scenario.id] = buf.toString('base64')
      } catch { /* skip */ }
    }
    for (const log of result.step_logs ?? []) {
      if (log.screenshot_path) {
        try {
          const buf = await fs.readFile(log.screenshot_path)
          stepScreenshotCache[log.screenshot_path] = buf.toString('base64')
        } catch { /* skip */ }
      }
    }
  }

  const explorationScreenshots: Record<string, string> = {}
  for (const exp of explorations) {
    if (exp.screenshot_path) {
      try {
        const buf = await fs.readFile(exp.screenshot_path)
        explorationScreenshots[exp.route] = buf.toString('base64')
      } catch { /* skip */ }
    }
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Vibe Test Report — ${productModel.project_name}</title>
<style>
${CSS}
</style>
</head>
<body>
<div class="container">

<header>
  <h1>Vibe Test Report</h1>
  <p>${productModel.project_name} &middot; ${config.url} &middot; ${new Date().toLocaleString()}</p>
  <div class="meta-grid">
    <div class="meta-item"><div class="label">Framework</div><div class="value">${productModel.framework}</div></div>
    <div class="meta-item"><div class="label">Routes</div><div class="value">${productModel.routes.length}</div></div>
    <div class="meta-item"><div class="label">Elements</div><div class="value">${totalElements}</div></div>
    <div class="meta-item"><div class="label">API Calls</div><div class="value">${totalApis}${apiErrors > 0 ? ` <span style="color:var(--fail)">(${apiErrors} errors)</span>` : ''}</div></div>
    <div class="meta-item"><div class="label">Duration</div><div class="value">${(totalMs / 1000).toFixed(1)}s</div></div>
  </div>
</header>

<div class="summary-bar">
  <div class="summary-stat pass"><div class="num">${passed.length}</div><div class="lbl">Passed</div></div>
  <div class="summary-stat fail"><div class="num">${failed.length}</div><div class="lbl">Failed</div></div>
  <div class="summary-stat error"><div class="num">${errored.length}</div><div class="lbl">Errors</div></div>
  <div class="summary-stat total"><div class="num">${totalElements}</div><div class="lbl">Elements Tested</div></div>
</div>

${failed.length + errored.length > 0 ? `<h2>Failures & Errors</h2>\n${[...failed, ...errored].map(r => renderScenarioCard(r, screenshotCache, stepScreenshotCache)).join('\n')}` : ''}

${passed.length > 0 ? `<h2>Passed Scenarios</h2>\n${passed.map(r => renderScenarioCard(r, screenshotCache, stepScreenshotCache)).join('\n')}` : ''}

${explorations.length > 0 ? renderExplorationSection(explorations, explorationScreenshots) : ''}

${coverageGaps.length > 0 ? renderCoverageGapsSection(coverageGaps) : ''}

${renderApiSection(explorations)}

${renderCoverageTable(productModel)}

${renderIntelligenceSection(recommendations)}

<footer>Generated by <strong>vibe-test</strong> v0.2.0 — No external LLM used</footer>
</div>

<div class="screenshot-modal" id="screenshotModal">
  <img id="modalImg" src="" alt="enlarged">
</div>

<script>
document.querySelectorAll('.card-header').forEach(h => {
  h.addEventListener('click', () => h.closest('.card').classList.toggle('open'))
})
// Enlarge step screenshots on click
document.querySelectorAll('.step-thumb').forEach(img => {
  img.addEventListener('click', e => {
    e.stopPropagation()
    const modal = document.getElementById('screenshotModal')
    document.getElementById('modalImg').src = img.src
    modal.classList.add('active')
  })
})
document.getElementById('screenshotModal').addEventListener('click', () => {
  document.getElementById('screenshotModal').classList.remove('active')
})
</script>
</body>
</html>`
}

// ─── Exploration Section ──────────────────────────────────────────────────────

function renderExplorationSection(explorations: PageExploration[], screenshots: Record<string, string>): string {
  const cards = explorations.map(exp => {
    const working = exp.interactions.filter(i => ['success', 'content_updated', 'dialog_opened', 'navigated', 'toast_shown'].includes(i.result)).length
    const broken = exp.interactions.filter(i => i.result === 'error').length
    const skipped = exp.interactions.filter(i => i.result === 'skipped').length
    const noChange = exp.interactions.filter(i => i.result === 'no_change').length

    const statusClass = broken > 0 ? 'fail' : 'pass'

    const interactionRows = exp.interactions.map(i => {
      const icon = i.result === 'success' || i.result === 'content_updated' ? '✅' :
                   i.result === 'dialog_opened' ? '🔲' :
                   i.result === 'navigated' ? '🔗' :
                   i.result === 'toast_shown' ? '💬' :
                   i.result === 'error' ? '❌' :
                   i.result === 'skipped' ? '⏭️' : '⚪'
      return `<tr>
        <td>${icon}</td>
        <td><strong>${esc(i.elementType)}</strong></td>
        <td>${esc(i.element)}</td>
        <td>${esc(i.action)}</td>
        <td><span class="badge ${i.result === 'error' ? 'fail' : i.result === 'skipped' ? 'medium' : 'pass'}">${i.result}</span></td>
        <td style="font-size:12px;color:var(--text-dim)">${esc(i.details.slice(0, 80))}</td>
      </tr>`
    }).join('\n')

    const screenshotHtml = screenshots[exp.route] ? `
      <div class="screenshot-container">
        <div class="screenshot-label">Page screenshot</div>
        <img src="data:image/png;base64,${screenshots[exp.route]}" alt="${esc(exp.route)}" loading="lazy">
      </div>` : ''

    return `<div class="card${broken > 0 ? ' open' : ''}">
    <div class="card-header">
      <div class="status-dot ${statusClass}"></div>
      <div class="title">${esc(exp.route)}</div>
      <div class="meta-tags">
        <span class="badge pass">${working} working</span>
        ${broken > 0 ? `<span class="badge fail">${broken} broken</span>` : ''}
        <span style="font-size:12px;color:var(--text-dim)">${exp.elements_discovered} elements, ${exp.duration_ms}ms</span>
      </div>
      <span class="chevron">▶</span>
    </div>
    <div class="card-body">
      <div class="info-grid">
        <div class="info-item"><span class="info-label">Elements</span><span>${Object.entries(exp.elements_by_type).map(([k, v]) => `${v} ${k}s`).join(', ')}</span></div>
        <div class="info-item"><span class="info-label">API Calls</span><span>${exp.api_calls.length}${exp.api_calls.filter(a => a.isError).length > 0 ? ` (${exp.api_calls.filter(a => a.isError).length} errors)` : ''}</span></div>
      </div>
      ${interactionRows ? `<table class="step-table">
        <thead><tr><th></th><th>Type</th><th>Element</th><th>Action</th><th>Result</th><th>Details</th></tr></thead>
        <tbody>${interactionRows}</tbody>
      </table>` : ''}
      ${screenshotHtml}
    </div>
  </div>`
  }).join('\n')

  return `<h2>Element Exploration</h2>\n${cards}`
}

// ─── Coverage Gaps Section ────────────────────────────────────────────────────

function renderCoverageGapsSection(gaps: CoverageGapSuggestion[]): string {
  const critical = gaps.filter(g => g.severity === 'critical')
  const important = gaps.filter(g => g.severity === 'important')
  const niceToHave = gaps.filter(g => g.severity === 'nice_to_have')

  const renderGap = (gap: CoverageGapSuggestion) => {
    const severityClass = gap.severity === 'critical' ? 'fail' : gap.severity === 'important' ? 'medium' : 'pass'
    const steps = gap.suggested_test.steps.map((s, i) => `<li>${esc(s)}</li>`).join('\n')
    return `<div class="card">
    <div class="card-header">
      <div class="status-dot ${severityClass === 'fail' ? 'fail' : severityClass === 'medium' ? 'error' : 'pass'}"></div>
      <div class="title">${esc(gap.missing)}</div>
      <div class="meta-tags">
        <span class="badge ${severityClass}">${gap.severity.replace('_', ' ')}</span>
        <code>${esc(gap.route)}</code>
      </div>
      <span class="chevron">▶</span>
    </div>
    <div class="card-body">
      <div style="margin-bottom:12px;font-weight:600">Suggested test: ${esc(gap.suggested_test.name)}</div>
      <ol style="padding-left:20px;font-size:13px;line-height:2">${steps}</ol>
    </div>
  </div>`
  }

  return `<h2>Coverage Gaps & Suggested Tests</h2>
  <p style="color:var(--text-dim);font-size:14px;margin-bottom:16px">${gaps.length} areas missing test coverage. These are inferred from code analysis and runtime exploration.</p>
  ${critical.length > 0 ? `<h3 style="color:var(--fail);font-size:14px;margin:12px 0 8px">Critical (${critical.length})</h3>\n${critical.map(renderGap).join('\n')}` : ''}
  ${important.length > 0 ? `<h3 style="color:var(--warn);font-size:14px;margin:12px 0 8px">Important (${important.length})</h3>\n${important.map(renderGap).join('\n')}` : ''}
  ${niceToHave.length > 0 ? `<h3 style="color:var(--pass);font-size:14px;margin:12px 0 8px">Nice to Have (${niceToHave.length})</h3>\n${niceToHave.map(renderGap).join('\n')}` : ''}`
}

// ─── API Monitoring Section ───────────────────────────────────────────────────

function renderApiSection(explorations: PageExploration[]): string {
  const allApis = explorations.flatMap(e => e.api_calls.map(a => ({ ...a, route: e.route })))
  if (allApis.length === 0) return ''

  const errors = allApis.filter(a => a.isError)
  const byEndpoint = new Map<string, { method: string; path: string; count: number; errors: number; avgTime: number }>()

  for (const api of allApis) {
    const key = `${api.method} ${api.path}`
    const existing = byEndpoint.get(key)
    if (existing) {
      existing.count++
      if (api.isError) existing.errors++
      existing.avgTime = Math.round((existing.avgTime * (existing.count - 1) + api.responseTime_ms) / existing.count)
    } else {
      byEndpoint.set(key, { method: api.method, path: api.path, count: 1, errors: api.isError ? 1 : 0, avgTime: api.responseTime_ms })
    }
  }

  const rows = [...byEndpoint.values()].map(api => {
    const statusClass = api.errors > 0 ? 'color:var(--fail)' : 'color:var(--pass)'
    return `<tr>
      <td><code>${esc(api.method)}</code></td>
      <td><code>${esc(api.path)}</code></td>
      <td>${api.count}</td>
      <td style="${statusClass}">${api.errors > 0 ? `${api.errors} errors` : 'OK'}</td>
      <td>${api.avgTime}ms</td>
    </tr>`
  }).join('\n')

  return `<h2>API Monitoring</h2>
  <p style="color:var(--text-dim);font-size:14px;margin-bottom:12px">${allApis.length} API calls observed${errors.length > 0 ? `, <span style="color:var(--fail)">${errors.length} errors</span>` : ''}</p>
  <div class="section-table">
    <table>
      <thead><tr><th>Method</th><th>Endpoint</th><th>Calls</th><th>Status</th><th>Avg Time</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
  </div>`
}

// ─── Coverage Table ───────────────────────────────────────────────────────────

function renderCoverageTable(productModel: ProductModel): string {
  const routeRows = productModel.routes.map(r => {
    const covered = productModel.coverage[r.path]
    return `<tr>
      <td><code>${r.path}</code></td>
      <td>${r.type}</td>
      <td>${r.requires_auth ? 'Yes' : 'No'}</td>
      <td>${covered?.tested ? '<span class="badge pass">Tested</span>' : '<span class="badge fail">No tests</span>'}</td>
    </tr>`
  }).join('\n')

  return `<h2>Route Coverage</h2>
  <div class="section-table">
    <table>
      <thead><tr><th>Route</th><th>Type</th><th>Auth</th><th>Tested</th></tr></thead>
      <tbody>${routeRows}</tbody>
    </table>
  </div>`
}

// ─── Scenario Card ────────────────────────────────────────────────────────────

function renderScenarioCard(result: TestResult, screenshots: Record<string, string>, stepScreenshots: Record<string, string>): string {
  const s = result.scenario
  const status = result.status
  const verdictClass = status === 'pass' ? 'pass-verdict' : status === 'fail' ? 'fail-verdict' : 'error-verdict'
  const explanation = result.ai_verdict ?? result.failure_reason ?? ''

  const navPath = result.navigated_url ? extractPath(result.navigated_url) : s.route
  const finalPath = result.current_url ? extractPath(result.current_url) : ''
  const wasRedirected = navPath !== finalPath && finalPath

  const stepRows = (result.step_logs ?? []).map(log => {
    const icon = log.status === 'ok' ? '✅' : log.status === 'failed' ? '❌' : '⏭️'
    const sel = log.selector_used ? `<code>${esc(log.selector_used)}</code>` : '—'
    const urlPath = extractPath(log.url_after)
    const err = log.error ? `<br><span style="color:var(--fail);font-size:11px">${esc(log.error.slice(0, 80))}</span>` : ''
    const stepScreenB64 = log.screenshot_path ? stepScreenshots[log.screenshot_path] : undefined
    const screenshotCell = stepScreenB64
      ? `<td class="step-screenshot-cell"><img src="data:image/png;base64,${stepScreenB64}" alt="step" class="step-thumb" loading="lazy"></td>`
      : `<td></td>`
    return `<tr>
      <td>${icon}</td>
      <td><strong>${log.step.action}</strong></td>
      <td>${esc(log.step.description)}${err}</td>
      <td>${sel}</td>
      <td><code>${esc(urlPath)}</code></td>
      <td>${log.duration_ms}ms</td>
      ${screenshotCell}
    </tr>`
  }).join('\n')

  const screenshotB64 = screenshots[s.id]
  const screenshotHtml = screenshotB64 ? `
    <div class="screenshot-container">
      <div class="screenshot-label">Screenshot at end of test</div>
      <img src="data:image/png;base64,${screenshotB64}" alt="${esc(s.name)}" loading="lazy">
    </div>` : ''

  const redirectNote = wasRedirected ? `
    <div class="redirect-note">
      Redirect: <code>${esc(navPath)}</code> → <code>${esc(finalPath)}</code>
      ${finalPath.includes('login') ? ' — requires authentication' : ''}
    </div>` : ''

  return `<div class="card${status !== 'pass' ? ' open' : ''}">
  <div class="card-header">
    <div class="status-dot ${status}"></div>
    <div class="title">${esc(s.name)}</div>
    <div class="meta-tags">
      <span class="badge ${s.priority}">${s.priority}</span>
      <span class="badge ${status}">${status}</span>
      <span style="font-size:12px;color:var(--text-dim)">${result.duration_ms}ms</span>
    </div>
    <span class="chevron">▶</span>
  </div>
  <div class="card-body">
    <div class="verdict ${verdictClass}">${esc(explanation)}</div>
    ${redirectNote}
    <div class="info-grid">
      <div class="info-item"><span class="info-label">Route</span><code>${esc(s.route)}</code></div>
      <div class="info-item"><span class="info-label">Expected</span><span>${esc(s.expected_outcome)}</span></div>
    </div>
    ${stepRows ? `<table class="step-table">
      <thead><tr><th></th><th>Action</th><th>Description</th><th>Selector</th><th>URL</th><th>Time</th><th>Screenshot</th></tr></thead>
      <tbody>${stepRows}</tbody>
    </table>` : ''}
    ${screenshotHtml}
  </div>
</div>`
}

// ─── Intelligence Section ─────────────────────────────────────────────────────

function renderIntelligenceSection(recs?: MemoryRecommendations): string {
  if (!recs || recs.first_run) {
    return `<h2>Intelligence</h2>
    <div class="card open"><div class="card-body">
      <p style="color:var(--text-dim)">First run complete. Future runs will use learned patterns for faster, smarter testing.</p>
    </div></div>`
  }

  const authStatus = recs.auth_intel?.session_established
    ? `<span style="color:var(--pass)">Working</span> (login: <code>${esc(recs.auth_intel.login_route)}</code>)`
    : `<span style="color:var(--warn)">Not established</span>`

  return `<h2>Intelligence</h2>
  <div class="card open"><div class="card-body">
    <div class="info-grid">
      <div class="info-item"><span class="info-label">Auth</span><span>${authStatus}</span></div>
      <div class="info-item"><span class="info-label">Selectors</span><span>${Object.keys(recs.selector_hints).length} learned</span></div>
      <div class="info-item"><span class="info-label">Auth Routes</span><span>${[...recs.auth_routes].map(r => `<code>${esc(r)}</code>`).join(', ') || 'None'}</span></div>
    </div>
  </div></div>`
}

function extractPath(url: string): string {
  try { return new URL(url).pathname } catch { return url }
}

function esc(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

// ─── CSS ──────────────────────────────────────────────────────────────────────

const CSS = `
:root {
  --bg: #0f1117; --surface: #1a1d27; --surface2: #232733; --border: #2e3345;
  --text: #e1e4ed; --text-dim: #8b92a8;
  --pass: #22c55e; --pass-bg: rgba(34,197,94,0.08);
  --fail: #ef4444; --fail-bg: rgba(239,68,68,0.08);
  --warn: #f59e0b; --warn-bg: rgba(245,158,11,0.08);
  --accent: #6366f1; --accent-bg: rgba(99,102,241,0.08);
  --radius: 10px;
}
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: var(--bg); color: var(--text); line-height: 1.6; }
.container { max-width: 1100px; margin: 0 auto; padding: 32px 24px; }
header { padding: 40px 0 32px; border-bottom: 1px solid var(--border); margin-bottom: 32px; }
header h1 { font-size: 28px; font-weight: 700; color: #fff; }
header p { color: var(--text-dim); font-size: 14px; }
.meta-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 12px; margin-top: 20px; }
.meta-item { background: var(--surface); border: 1px solid var(--border); border-radius: var(--radius); padding: 14px 16px; }
.meta-item .label { font-size: 11px; color: var(--text-dim); text-transform: uppercase; letter-spacing: 0.5px; }
.meta-item .value { font-size: 18px; font-weight: 600; margin-top: 4px; }
.summary-bar { display: flex; gap: 16px; margin: 28px 0; flex-wrap: wrap; }
.summary-stat { flex: 1; min-width: 140px; padding: 20px; border-radius: var(--radius); text-align: center; border: 1px solid var(--border); }
.summary-stat.pass { background: var(--pass-bg); border-color: rgba(34,197,94,0.2); }
.summary-stat.fail { background: var(--fail-bg); border-color: rgba(239,68,68,0.2); }
.summary-stat.error { background: var(--warn-bg); border-color: rgba(245,158,11,0.2); }
.summary-stat.total { background: var(--accent-bg); border-color: rgba(99,102,241,0.2); }
.summary-stat .num { font-size: 36px; font-weight: 700; }
.summary-stat.pass .num { color: var(--pass); }
.summary-stat.fail .num { color: var(--fail); }
.summary-stat.error .num { color: var(--warn); }
.summary-stat.total .num { color: var(--accent); }
.summary-stat .lbl { font-size: 12px; color: var(--text-dim); text-transform: uppercase; letter-spacing: 0.5px; margin-top: 4px; }
h2 { font-size: 20px; font-weight: 600; margin: 36px 0 16px; padding-bottom: 8px; border-bottom: 1px solid var(--border); }
h3 { font-size: 14px; font-weight: 600; margin: 16px 0 8px; }
.card { background: var(--surface); border: 1px solid var(--border); border-radius: var(--radius); margin-bottom: 12px; overflow: hidden; }
.card-header { padding: 14px 20px; display: flex; align-items: center; gap: 12px; cursor: pointer; user-select: none; }
.card-header:hover { background: var(--surface2); }
.card-header .status-dot { width: 10px; height: 10px; border-radius: 50%; flex-shrink: 0; }
.card-header .status-dot.pass { background: var(--pass); }
.card-header .status-dot.fail { background: var(--fail); }
.card-header .status-dot.error { background: var(--warn); }
.card-header .title { font-weight: 600; flex: 1; font-size: 14px; }
.card-header .meta-tags { display: flex; gap: 8px; align-items: center; }
.badge { font-size: 11px; padding: 2px 8px; border-radius: 4px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.3px; }
.badge.pass { background: var(--pass-bg); color: var(--pass); border: 1px solid rgba(34,197,94,0.2); }
.badge.fail { background: var(--fail-bg); color: var(--fail); border: 1px solid rgba(239,68,68,0.2); }
.badge.error, .badge.medium { background: var(--warn-bg); color: var(--warn); border: 1px solid rgba(245,158,11,0.2); }
.badge.high { background: var(--fail-bg); color: var(--fail); border: 1px solid rgba(239,68,68,0.2); }
.badge.low { background: var(--pass-bg); color: var(--pass); border: 1px solid rgba(34,197,94,0.2); }
.card-body { display: none; padding: 0 20px 20px; }
.card.open .card-body { display: block; }
.card.open .chevron { transform: rotate(90deg); }
.chevron { color: var(--text-dim); transition: transform 0.2s; font-size: 12px; }
.verdict { padding: 12px 16px; border-radius: 8px; margin-bottom: 16px; font-size: 14px; }
.verdict.fail-verdict { background: var(--fail-bg); border-left: 3px solid var(--fail); }
.verdict.pass-verdict { background: var(--pass-bg); border-left: 3px solid var(--pass); }
.verdict.error-verdict { background: var(--warn-bg); border-left: 3px solid var(--warn); }
.info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-bottom: 16px; font-size: 13px; }
.info-grid .info-item { display: flex; gap: 8px; }
.info-grid .info-label { color: var(--text-dim); min-width: 100px; }
table { width: 100%; border-collapse: collapse; font-size: 13px; margin: 12px 0; }
th { text-align: left; padding: 8px 12px; background: var(--surface2); color: var(--text-dim); font-weight: 600; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 1px solid var(--border); }
td { padding: 8px 12px; border-bottom: 1px solid var(--border); vertical-align: top; }
tr:last-child td { border-bottom: none; }
.screenshot-container { margin-top: 16px; border: 1px solid var(--border); border-radius: 8px; overflow: hidden; }
.screenshot-container img { width: 100%; display: block; }
.screenshot-label { font-size: 11px; color: var(--text-dim); padding: 8px 12px; background: var(--surface2); text-transform: uppercase; letter-spacing: 0.5px; }
.step-table td:first-child { width: 30px; text-align: center; }
.step-screenshot-cell { width: 80px; }
.step-thumb { width: 70px; height: 45px; object-fit: cover; border-radius: 4px; border: 1px solid var(--border); cursor: pointer; transition: transform 0.15s; }
.step-thumb:hover { transform: scale(2.5); z-index: 100; position: relative; box-shadow: 0 8px 24px rgba(0,0,0,0.6); }
.screenshot-modal { display: none; position: fixed; inset: 0; background: rgba(0,0,0,0.85); z-index: 1000; align-items: center; justify-content: center; cursor: zoom-out; }
.screenshot-modal.active { display: flex; }
.screenshot-modal img { max-width: 90vw; max-height: 90vh; border-radius: 8px; }
code { background: var(--surface2); padding: 2px 6px; border-radius: 4px; font-size: 12px; font-family: 'SF Mono', 'Fira Code', monospace; }
.section-table { margin-bottom: 8px; }
.section-table table { background: var(--surface); border-radius: var(--radius); overflow: hidden; border: 1px solid var(--border); }
.redirect-note { background: var(--warn-bg); border-left: 3px solid var(--warn); padding: 10px 14px; border-radius: 0 6px 6px 0; margin-bottom: 16px; font-size: 13px; color: var(--warn); }
footer { margin-top: 48px; padding: 20px 0; border-top: 1px solid var(--border); text-align: center; font-size: 12px; color: var(--text-dim); }
ol { color: var(--text); }
`
