import { TestResult, ProductModel, StepLog } from '../../types/index.js'
import { VibeConfig } from '../../types/config.js'
import path from 'path'

export function generateMarkdownReport(
  results: TestResult[],
  productModel: ProductModel,
  config: VibeConfig
): string {
  const passed  = results.filter(r => r.status === 'pass')
  const failed  = results.filter(r => r.status === 'fail')
  const errored = results.filter(r => r.status === 'error')
  const totalMs = results.reduce((sum, r) => sum + r.duration_ms, 0)
  const reportDir = path.join(productModel.codebase_path, '.vibe')

  const lines: string[] = []

  // ── Header ──────────────────────────────────────────────────────────
  lines.push(`# Vibe Test Report`)
  lines.push(``)
  lines.push(`| Property | Value |`)
  lines.push(`|----------|-------|`)
  lines.push(`| **Project** | ${productModel.project_name} |`)
  lines.push(`| **URL** | ${config.url} |`)
  lines.push(`| **Framework** | ${productModel.framework} |`)
  lines.push(`| **Mode** | ${config.mode ?? 'deep'} |`)
  lines.push(`| **Run at** | ${new Date().toLocaleString()} |`)
  lines.push(`| **Duration** | ${(totalMs / 1000).toFixed(1)}s |`)
  lines.push(`| **Routes scanned** | ${productModel.routes.length} |`)
  lines.push(`| **Gaps found** | ${productModel.gaps.length} (${productModel.gaps.filter(g => g.priority === 'high').length} high priority) |`)
  lines.push(``)

  // ── Summary ─────────────────────────────────────────────────────────
  lines.push(`## Results Summary`)
  lines.push(``)
  lines.push(`| Status | Count | Scenarios |`)
  lines.push(`|--------|-------|-----------|`)
  lines.push(`| ✅ Passed | **${passed.length}** | ${passed.map(r => r.scenario.name).join(', ') || '—'} |`)
  lines.push(`| ❌ Failed | **${failed.length}** | ${failed.map(r => r.scenario.name).join(', ') || '—'} |`)
  lines.push(`| ⚠️ Error | **${errored.length}** | ${errored.map(r => r.scenario.name).join(', ') || '—'} |`)
  lines.push(`| **Total** | **${results.length}** | |`)
  lines.push(``)

  // ── Detailed results ────────────────────────────────────────────────
  lines.push(`---`)
  lines.push(``)

  // Failures and errors first
  if (failed.length > 0 || errored.length > 0) {
    lines.push(`## ❌ Failures & Errors`)
    lines.push(``)
    for (const result of [...failed, ...errored]) {
      renderScenarioDetail(lines, result, reportDir)
    }
  }

  // Then passes
  if (passed.length > 0) {
    lines.push(`## ✅ Passed Scenarios`)
    lines.push(``)
    for (const result of passed) {
      renderScenarioDetail(lines, result, reportDir)
    }
  }

  // ── Coverage context ────────────────────────────────────────────────
  lines.push(`---`)
  lines.push(``)
  lines.push(`## Coverage Analysis`)
  lines.push(``)

  // Routes table
  lines.push(`### Routes Discovered`)
  lines.push(``)
  lines.push(`| Route | Type | Auth Required | Tested |`)
  lines.push(`|-------|------|---------------|--------|`)
  for (const route of productModel.routes) {
    const covered = productModel.coverage[route.path]
    const tested = covered?.tested ? '✅ Yes' : '❌ No'
    lines.push(`| \`${route.path}\` | ${route.type} | ${route.requires_auth ? 'Yes' : 'No'} | ${tested} |`)
  }
  lines.push(``)

  // Gaps
  if (productModel.gaps.length > 0) {
    lines.push(`### Test Gaps`)
    lines.push(``)
    lines.push(`| Route | Priority | Reason | Untested Aspects |`)
    lines.push(`|-------|----------|--------|-----------------|`)
    for (const gap of productModel.gaps) {
      const aspects = gap.untested_aspects?.join(', ') || '—'
      const priorityIcon = gap.priority === 'high' ? '🔴' : gap.priority === 'medium' ? '🟡' : '🟢'
      lines.push(`| \`${gap.route}\` | ${priorityIcon} ${gap.priority} | ${gap.reason.replace(/_/g, ' ')} | ${aspects} |`)
    }
    lines.push(``)
  }

  return lines.join('\n')
}

function renderScenarioDetail(lines: string[], result: TestResult, reportDir: string): void {
  const statusIcon = result.status === 'pass' ? '✅' : result.status === 'fail' ? '❌' : '⚠️'

  lines.push(`### ${statusIcon} ${result.scenario.name}`)
  lines.push(``)
  lines.push(`| | |`)
  lines.push(`|---|---|`)
  lines.push(`| **ID** | ${result.scenario.id} |`)
  lines.push(`| **Route** | \`${result.scenario.route}\` |`)
  lines.push(`| **Priority** | ${result.scenario.priority} |`)
  lines.push(`| **Status** | **${result.status.toUpperCase()}** |`)
  lines.push(`| **Duration** | ${result.duration_ms}ms |`)
  lines.push(`| **Generated by** | ${result.scenario.generated_by} |`)
  if (result.navigated_url) lines.push(`| **Navigated to** | ${result.navigated_url} |`)
  if (result.current_url)   lines.push(`| **Final URL** | ${result.current_url} |`)
  lines.push(``)

  // Verdict / explanation
  if (result.ai_verdict) {
    lines.push(`**What happened:** ${result.ai_verdict}`)
    lines.push(``)
  }
  if (result.failure_reason) {
    lines.push(`**Error:** \`${result.failure_reason}\``)
    lines.push(``)
  }

  // Detect and explain redirect
  if (result.navigated_url && result.current_url) {
    const navPath = extractPath(result.navigated_url)
    const finalPath = extractPath(result.current_url)
    if (navPath !== finalPath) {
      lines.push(`> **Redirect detected:** Browser was sent to \`${navPath}\` but ended up at \`${finalPath}\`.`)
      if (finalPath.includes('login')) {
        lines.push(`> This likely means the route requires authentication.`)
      }
      lines.push(``)
    }
  }

  // Step-by-step execution log
  if (result.step_logs && result.step_logs.length > 0) {
    lines.push(`<details>`)
    lines.push(`<summary><b>Step-by-step execution (${result.step_logs.length} steps)</b></summary>`)
    lines.push(``)
    lines.push(`| # | Action | Description | Selector Used | URL After | Time | Status |`)
    lines.push(`|---|--------|-------------|---------------|-----------|------|--------|`)

    result.step_logs.forEach((log, i) => {
      const statusIcon = log.status === 'ok' ? '✅' : log.status === 'failed' ? '❌' : '⏭️'
      const selectorCol = log.selector_used ? `\`${log.selector_used}\`` : '—'
      const urlPath = extractPath(log.url_after)
      const errorNote = log.error ? ` ⚠️ ${truncate(log.error, 40)}` : ''
      lines.push(`| ${i + 1} | ${log.step.action} | ${truncate(log.step.description, 45)} | ${selectorCol} | \`${urlPath}\` | ${log.duration_ms}ms | ${statusIcon}${errorNote} |`)
    })

    lines.push(``)
    lines.push(`</details>`)
    lines.push(``)
  }

  // Screenshot
  if (result.screenshot_path) {
    const relativePath = path.relative(reportDir, result.screenshot_path)
    lines.push(`**Screenshot:**`)
    lines.push(``)
    lines.push(`![${result.scenario.name}](${relativePath})`)
    lines.push(``)
  }

  lines.push(`**Expected outcome:** ${result.scenario.expected_outcome}`)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)
}

function extractPath(url: string): string {
  try {
    return new URL(url).pathname
  } catch {
    return url
  }
}

function truncate(str: string, maxLen: number): string {
  return str.length > maxLen ? str.slice(0, maxLen - 1) + '…' : str
}
